-- Products fields
ALTER TABLE products ADD COLUMN IF NOT EXISTS title_en VARCHAR(500);
ALTER TABLE products ADD COLUMN IF NOT EXISTS category VARCHAR(100);
ALTER TABLE products ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS description_en TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS moq INTEGER;
ALTER TABLE products ADD COLUMN IF NOT EXISTS lead_time_sample VARCHAR(100);
ALTER TABLE products ADD COLUMN IF NOT EXISTS lead_time_production VARCHAR(100);
ALTER TABLE products ADD COLUMN IF NOT EXISTS certifications JSON;
ALTER TABLE products ADD COLUMN IF NOT EXISTS target_markets JSON;
ALTER TABLE products ADD COLUMN IF NOT EXISTS image TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS gallery_images JSON;
ALTER TABLE products ADD COLUMN IF NOT EXISTS specs JSON;
ALTER TABLE products ADD COLUMN IF NOT EXISTS features JSON;
ALTER TABLE products ADD COLUMN IF NOT EXISTS custom_options JSON;
ALTER TABLE products ADD COLUMN IF NOT EXISTS status VARCHAR(50);
ALTER TABLE products ADD COLUMN IF NOT EXISTS sort INTEGER;

-- FAQs fields
ALTER TABLE faqs ADD COLUMN IF NOT EXISTS question_en VARCHAR(500);
ALTER TABLE faqs ADD COLUMN IF NOT EXISTS answer TEXT;
ALTER TABLE faqs ADD COLUMN IF NOT EXISTS answer_en TEXT;
ALTER TABLE faqs ADD COLUMN IF NOT EXISTS category VARCHAR(100);
ALTER TABLE faqs ADD COLUMN IF NOT EXISTS sort INTEGER;

-- Blogs fields
ALTER TABLE blogs ADD COLUMN IF NOT EXISTS title_en VARCHAR(500);
ALTER TABLE blogs ADD COLUMN IF NOT EXISTS excerpt TEXT;
ALTER TABLE blogs ADD COLUMN IF NOT EXISTS excerpt_en TEXT;
ALTER TABLE blogs ADD COLUMN IF NOT EXISTS content TEXT;
ALTER TABLE blogs ADD COLUMN IF NOT EXISTS content_en TEXT;
ALTER TABLE blogs ADD COLUMN IF NOT EXISTS cover_image TEXT;
ALTER TABLE blogs ADD COLUMN IF NOT EXISTS author VARCHAR(200);
ALTER TABLE blogs ADD COLUMN IF NOT EXISTS tags JSON;
ALTER TABLE blogs ADD COLUMN IF NOT EXISTS date_published TIMESTAMP;
ALTER TABLE blogs ADD COLUMN IF NOT EXISTS status VARCHAR(50);
